### ISSUE TITLE
[Q] - Any way to create container, leave it working and call tesseract from it?

### ISSUE THREAD

**Issue by edwvee** [jitesoft/docker-tesseract-ocr#5]
```
docker run -v /path/to/image/img.jpg:/tmp/img.jpg jitesoft/tesseract-ocr /tmp/img.jpg stdout
```
called each time takes too much to create container. Tesseract installed on host works much faster. I tried to run it with looped bash, but whatever command you pass it calls tesseract. Just trying to call bash (or whatever other command):
```
$ docker run --rm jitesoft/tesseract-ocr bash
Usage:
  tesseract --help | --help-extra | --version
  tesseract --list-langs
  tesseract imagename outputbase [options...] [configfile...]

OCR options:
  -l LANG[+LANG]        Specify language(s) used for OCR.
NOTE: These options must occur before any configfile.

Single options:
  --help                Show this help message.
  --help-extra          Show extra help for advanced users.
  --version             Show version information.
  --list-langs          List available languages for tesseract engine.
```

**Comment by doctorleach** [comment]
If I understand you correctly, the following should do the job for you.  I think your omission is the --entrypoint flag.

This works for me:

docker run -it -v /Users/myname/tessdata:/usr/local/share/files --rm --name ocr --entrypoint bash 1ae3b885ba1f

where -v gives the drive mapping, --name names the container "ocr" and the hex at the end is the id of the docker image (in my case based on jitesoft/tesseract-ocr)

This should open a bash prompt inside the container; from there, change to the directory that has your image files to be processed and run:

tesseract SCAN0013.jpg [OUT]

where SCAN0013.jpg is the image file to be converted and the resulting output file has the naming convention specified in OUT

**Comment by edwvee** [comment]
> If I understand you correctly, the following should do the job for you. I think your omission is the --entrypoint flag.
> 
> This works for me:
> 
> docker run -it -v /Users/myname/tessdata:/usr/local/share/files --rm --name ocr --entrypoint bash 1ae3b885ba1f
> 
> where -v gives the drive mapping, --name names the container "ocr" and the hex at the end is the id of the docker image (in my case based on jitesoft/tesseract-ocr)
> 
> This should open a bash prompt inside the container; from there, change to the directory that has your image files to be processed and run:
> 
> tesseract SCAN0013.jpg [OUT]
> 
> where SCAN0013.jpg is the image file to be converted and the resulting output file has the naming convention specified in OUT

Thank you. What I needed is to start container once and to call tesseract command, not create or even start container each time. So how I figured out with your help:
1.  Create container so it runs forever:
```
docker run -d -v "{directory_to_mount}:/app" --name ocr --entrypoint bash jitesoft/tesseract-ocr -c 'while true; do sleep 1; done'
```
2. Call tesseract:
```
docker exec -it ocr tesseract /app/{path_in_mounted_directory} stdout
``` 
So it's fast like a thunder in comparison to readme's way to launch. It would be good to add this to readme.  I just don't know how to describe it correctly.

**Comment by doctorleach** [comment]
Glad you were able to make it work.  Always good to have a fast implementation.

**Comment by Johannestegner** [comment]
Hi there!

It seems like you figured out a good way to do what you needed!
Will add a note to the readme (if you don't want to do it as a PR!) asap.

Closing this issue for now seeing the issue was resolved :)
